# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mhsa/mhsa.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa || ORIG_REF_NAME==mhsa} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_mhsa_top_0_0/mhsa_mhsa_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_mhsa_top_0_0 || ORIG_REF_NAME==mhsa_mhsa_top_0_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_zynq_ultra_ps_e_0_0/mhsa_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mhsa_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_proc_sys_reset_0_0/mhsa_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_proc_sys_reset_0_0 || ORIG_REF_NAME==mhsa_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_smartconnect_0_0/mhsa_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_smartconnect_0_0 || ORIG_REF_NAME==mhsa_smartconnect_0_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_smartconnect_1_0/mhsa_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_smartconnect_1_0 || ORIG_REF_NAME==mhsa_smartconnect_1_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_smartconnect_2_0/mhsa_smartconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_smartconnect_2_0 || ORIG_REF_NAME==mhsa_smartconnect_2_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_smartconnect_3_0/mhsa_smartconnect_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_smartconnect_3_0 || ORIG_REF_NAME==mhsa_smartconnect_3_0} -quiet] -quiet

# IP: bd/mhsa/ip/mhsa_smartconnect_4_0/mhsa_smartconnect_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_smartconnect_4_0 || ORIG_REF_NAME==mhsa_smartconnect_4_0} -quiet] -quiet

# XDC: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/mhsa_ooc.xdc
