-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mhsa_top_mhsa_top_Pipeline_store_o is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_o_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_o_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_o_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_o_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_o_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_o_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_o_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_o_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_o_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_o_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_o_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_o_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_o_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_o_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_o_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_o_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_o_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_o_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_o_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_o_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_o_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_o_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_o_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_o_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_o_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_o_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_o_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln107 : IN STD_LOGIC_VECTOR (61 downto 0);
    O_row_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_ce0 : OUT STD_LOGIC;
    O_row_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_1_ce0 : OUT STD_LOGIC;
    O_row_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_2_ce0 : OUT STD_LOGIC;
    O_row_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_3_ce0 : OUT STD_LOGIC;
    O_row_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_4_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_4_ce0 : OUT STD_LOGIC;
    O_row_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_5_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_5_ce0 : OUT STD_LOGIC;
    O_row_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_6_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_6_ce0 : OUT STD_LOGIC;
    O_row_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_7_ce0 : OUT STD_LOGIC;
    O_row_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_8_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_8_ce0 : OUT STD_LOGIC;
    O_row_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_9_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_9_ce0 : OUT STD_LOGIC;
    O_row_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_10_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_10_ce0 : OUT STD_LOGIC;
    O_row_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_11_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_11_ce0 : OUT STD_LOGIC;
    O_row_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_12_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_12_ce0 : OUT STD_LOGIC;
    O_row_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_13_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_13_ce0 : OUT STD_LOGIC;
    O_row_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_14_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_14_ce0 : OUT STD_LOGIC;
    O_row_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    O_row_15_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    O_row_15_ce0 : OUT STD_LOGIC;
    O_row_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mhsa_top_mhsa_top_Pipeline_store_o is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln107_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_o_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln107_fu_372_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln107_reg_504 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_589 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln107_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal j_fu_122 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln107_fu_366_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal O_row_ce0_local : STD_LOGIC;
    signal O_row_1_ce0_local : STD_LOGIC;
    signal O_row_2_ce0_local : STD_LOGIC;
    signal O_row_3_ce0_local : STD_LOGIC;
    signal O_row_4_ce0_local : STD_LOGIC;
    signal O_row_5_ce0_local : STD_LOGIC;
    signal O_row_6_ce0_local : STD_LOGIC;
    signal O_row_7_ce0_local : STD_LOGIC;
    signal O_row_8_ce0_local : STD_LOGIC;
    signal O_row_9_ce0_local : STD_LOGIC;
    signal O_row_10_ce0_local : STD_LOGIC;
    signal O_row_11_ce0_local : STD_LOGIC;
    signal O_row_12_ce0_local : STD_LOGIC;
    signal O_row_13_ce0_local : STD_LOGIC;
    signal O_row_14_ce0_local : STD_LOGIC;
    signal O_row_15_ce0_local : STD_LOGIC;
    signal lshr_ln1_fu_376_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_411_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_411_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_411_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mhsa_top_sparsemux_33_4_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mhsa_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_32_1_1_U675 : component mhsa_top_sparsemux_33_4_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 32,
        CASE1 => "0001",
        din1_WIDTH => 32,
        CASE2 => "0010",
        din2_WIDTH => 32,
        CASE3 => "0011",
        din3_WIDTH => 32,
        CASE4 => "0100",
        din4_WIDTH => 32,
        CASE5 => "0101",
        din5_WIDTH => 32,
        CASE6 => "0110",
        din6_WIDTH => 32,
        CASE7 => "0111",
        din7_WIDTH => 32,
        CASE8 => "1000",
        din8_WIDTH => 32,
        CASE9 => "1001",
        din9_WIDTH => 32,
        CASE10 => "1010",
        din10_WIDTH => 32,
        CASE11 => "1011",
        din11_WIDTH => 32,
        CASE12 => "1100",
        din12_WIDTH => 32,
        CASE13 => "1101",
        din13_WIDTH => 32,
        CASE14 => "1110",
        din14_WIDTH => 32,
        CASE15 => "1111",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => O_row_q0,
        din1 => O_row_1_q0,
        din2 => O_row_2_q0,
        din3 => O_row_3_q0,
        din4 => O_row_4_q0,
        din5 => O_row_5_q0,
        din6 => O_row_6_q0,
        din7 => O_row_7_q0,
        din8 => O_row_8_q0,
        din9 => O_row_9_q0,
        din10 => O_row_10_q0,
        din11 => O_row_11_q0,
        din12 => O_row_12_q0,
        din13 => O_row_13_q0,
        din14 => O_row_14_q0,
        din15 => O_row_15_q0,
        def => tmp_fu_411_p33,
        sel => trunc_ln107_reg_504,
        dout => tmp_fu_411_p35);

    flow_control_loop_pipe_sequential_init_U : component mhsa_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln107_fu_360_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_122 <= add_ln107_fu_366_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_122 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                tmp_reg_589 <= tmp_fu_411_p35;
                trunc_ln107_reg_504 <= trunc_ln107_fu_372_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    O_row_10_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_10_ce0 <= O_row_10_ce0_local;

    O_row_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_10_ce0_local <= ap_const_logic_1;
        else 
            O_row_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_11_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_11_ce0 <= O_row_11_ce0_local;

    O_row_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_11_ce0_local <= ap_const_logic_1;
        else 
            O_row_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_12_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_12_ce0 <= O_row_12_ce0_local;

    O_row_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_12_ce0_local <= ap_const_logic_1;
        else 
            O_row_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_13_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_13_ce0 <= O_row_13_ce0_local;

    O_row_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_13_ce0_local <= ap_const_logic_1;
        else 
            O_row_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_14_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_14_ce0 <= O_row_14_ce0_local;

    O_row_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_14_ce0_local <= ap_const_logic_1;
        else 
            O_row_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_15_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_15_ce0 <= O_row_15_ce0_local;

    O_row_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_15_ce0_local <= ap_const_logic_1;
        else 
            O_row_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_1_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_1_ce0 <= O_row_1_ce0_local;

    O_row_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_1_ce0_local <= ap_const_logic_1;
        else 
            O_row_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_2_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_2_ce0 <= O_row_2_ce0_local;

    O_row_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_2_ce0_local <= ap_const_logic_1;
        else 
            O_row_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_3_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_3_ce0 <= O_row_3_ce0_local;

    O_row_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_3_ce0_local <= ap_const_logic_1;
        else 
            O_row_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_4_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_4_ce0 <= O_row_4_ce0_local;

    O_row_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_4_ce0_local <= ap_const_logic_1;
        else 
            O_row_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_5_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_5_ce0 <= O_row_5_ce0_local;

    O_row_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_5_ce0_local <= ap_const_logic_1;
        else 
            O_row_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_6_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_6_ce0 <= O_row_6_ce0_local;

    O_row_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_6_ce0_local <= ap_const_logic_1;
        else 
            O_row_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_7_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_7_ce0 <= O_row_7_ce0_local;

    O_row_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_7_ce0_local <= ap_const_logic_1;
        else 
            O_row_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_8_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_8_ce0 <= O_row_8_ce0_local;

    O_row_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_8_ce0_local <= ap_const_logic_1;
        else 
            O_row_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_9_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_9_ce0 <= O_row_9_ce0_local;

    O_row_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_9_ce0_local <= ap_const_logic_1;
        else 
            O_row_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    O_row_address0 <= zext_ln107_fu_386_p1(2 - 1 downto 0);
    O_row_ce0 <= O_row_ce0_local;

    O_row_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            O_row_ce0_local <= ap_const_logic_1;
        else 
            O_row_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln107_fu_366_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_o_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_o_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_o_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_o_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_o_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_o_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln107_fu_360_p2)
    begin
        if (((icmp_ln107_fu_360_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_122, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_122;
        end if; 
    end process;


    gmem_o_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_o_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_o_blk_n_W <= m_axi_gmem_o_0_WREADY;
        else 
            gmem_o_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln107_fu_360_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv7_40) else "0";
    lshr_ln1_fu_376_p4 <= ap_sig_allocacmp_j_1(5 downto 4);
    m_axi_gmem_o_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_o_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_o_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_o_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_o_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_o_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_o_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_o_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_o_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_o_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_o_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_o_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_o_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_o_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_o_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_o_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_o_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_o_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_o_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_o_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_o_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_o_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_o_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_o_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_o_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_o_0_RREADY <= ap_const_logic_0;
    m_axi_gmem_o_0_WDATA <= tmp_reg_589;
    m_axi_gmem_o_0_WID <= ap_const_lv1_0;
    m_axi_gmem_o_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_o_0_WSTRB <= ap_const_lv4_F;
    m_axi_gmem_o_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem_o_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem_o_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_o_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_411_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln107_fu_372_p1 <= ap_sig_allocacmp_j_1(4 - 1 downto 0);
    zext_ln107_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_376_p4),64));
end behav;
