// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mhsa_top_mhsa_top_Pipeline_load_kv_VITIS_LOOP_91_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_k_0_AWVALID,
        m_axi_gmem_k_0_AWREADY,
        m_axi_gmem_k_0_AWADDR,
        m_axi_gmem_k_0_AWID,
        m_axi_gmem_k_0_AWLEN,
        m_axi_gmem_k_0_AWSIZE,
        m_axi_gmem_k_0_AWBURST,
        m_axi_gmem_k_0_AWLOCK,
        m_axi_gmem_k_0_AWCACHE,
        m_axi_gmem_k_0_AWPROT,
        m_axi_gmem_k_0_AWQOS,
        m_axi_gmem_k_0_AWREGION,
        m_axi_gmem_k_0_AWUSER,
        m_axi_gmem_k_0_WVALID,
        m_axi_gmem_k_0_WREADY,
        m_axi_gmem_k_0_WDATA,
        m_axi_gmem_k_0_WSTRB,
        m_axi_gmem_k_0_WLAST,
        m_axi_gmem_k_0_WID,
        m_axi_gmem_k_0_WUSER,
        m_axi_gmem_k_0_ARVALID,
        m_axi_gmem_k_0_ARREADY,
        m_axi_gmem_k_0_ARADDR,
        m_axi_gmem_k_0_ARID,
        m_axi_gmem_k_0_ARLEN,
        m_axi_gmem_k_0_ARSIZE,
        m_axi_gmem_k_0_ARBURST,
        m_axi_gmem_k_0_ARLOCK,
        m_axi_gmem_k_0_ARCACHE,
        m_axi_gmem_k_0_ARPROT,
        m_axi_gmem_k_0_ARQOS,
        m_axi_gmem_k_0_ARREGION,
        m_axi_gmem_k_0_ARUSER,
        m_axi_gmem_k_0_RVALID,
        m_axi_gmem_k_0_RREADY,
        m_axi_gmem_k_0_RDATA,
        m_axi_gmem_k_0_RLAST,
        m_axi_gmem_k_0_RID,
        m_axi_gmem_k_0_RFIFONUM,
        m_axi_gmem_k_0_RUSER,
        m_axi_gmem_k_0_RRESP,
        m_axi_gmem_k_0_BVALID,
        m_axi_gmem_k_0_BREADY,
        m_axi_gmem_k_0_BRESP,
        m_axi_gmem_k_0_BID,
        m_axi_gmem_k_0_BUSER,
        m_axi_gmem_v_0_AWVALID,
        m_axi_gmem_v_0_AWREADY,
        m_axi_gmem_v_0_AWADDR,
        m_axi_gmem_v_0_AWID,
        m_axi_gmem_v_0_AWLEN,
        m_axi_gmem_v_0_AWSIZE,
        m_axi_gmem_v_0_AWBURST,
        m_axi_gmem_v_0_AWLOCK,
        m_axi_gmem_v_0_AWCACHE,
        m_axi_gmem_v_0_AWPROT,
        m_axi_gmem_v_0_AWQOS,
        m_axi_gmem_v_0_AWREGION,
        m_axi_gmem_v_0_AWUSER,
        m_axi_gmem_v_0_WVALID,
        m_axi_gmem_v_0_WREADY,
        m_axi_gmem_v_0_WDATA,
        m_axi_gmem_v_0_WSTRB,
        m_axi_gmem_v_0_WLAST,
        m_axi_gmem_v_0_WID,
        m_axi_gmem_v_0_WUSER,
        m_axi_gmem_v_0_ARVALID,
        m_axi_gmem_v_0_ARREADY,
        m_axi_gmem_v_0_ARADDR,
        m_axi_gmem_v_0_ARID,
        m_axi_gmem_v_0_ARLEN,
        m_axi_gmem_v_0_ARSIZE,
        m_axi_gmem_v_0_ARBURST,
        m_axi_gmem_v_0_ARLOCK,
        m_axi_gmem_v_0_ARCACHE,
        m_axi_gmem_v_0_ARPROT,
        m_axi_gmem_v_0_ARQOS,
        m_axi_gmem_v_0_ARREGION,
        m_axi_gmem_v_0_ARUSER,
        m_axi_gmem_v_0_RVALID,
        m_axi_gmem_v_0_RREADY,
        m_axi_gmem_v_0_RDATA,
        m_axi_gmem_v_0_RLAST,
        m_axi_gmem_v_0_RID,
        m_axi_gmem_v_0_RFIFONUM,
        m_axi_gmem_v_0_RUSER,
        m_axi_gmem_v_0_RRESP,
        m_axi_gmem_v_0_BVALID,
        m_axi_gmem_v_0_BREADY,
        m_axi_gmem_v_0_BRESP,
        m_axi_gmem_v_0_BID,
        m_axi_gmem_v_0_BUSER,
        zext_ln90,
        V,
        K,
        p_ZL5K_buf_0_address1,
        p_ZL5K_buf_0_ce1,
        p_ZL5K_buf_0_we1,
        p_ZL5K_buf_0_d1,
        p_ZL5V_buf_0_address1,
        p_ZL5V_buf_0_ce1,
        p_ZL5V_buf_0_we1,
        p_ZL5V_buf_0_d1,
        p_ZL5K_buf_1_address1,
        p_ZL5K_buf_1_ce1,
        p_ZL5K_buf_1_we1,
        p_ZL5K_buf_1_d1,
        p_ZL5V_buf_1_address1,
        p_ZL5V_buf_1_ce1,
        p_ZL5V_buf_1_we1,
        p_ZL5V_buf_1_d1,
        p_ZL5K_buf_2_address1,
        p_ZL5K_buf_2_ce1,
        p_ZL5K_buf_2_we1,
        p_ZL5K_buf_2_d1,
        p_ZL5V_buf_2_address1,
        p_ZL5V_buf_2_ce1,
        p_ZL5V_buf_2_we1,
        p_ZL5V_buf_2_d1,
        p_ZL5K_buf_3_address1,
        p_ZL5K_buf_3_ce1,
        p_ZL5K_buf_3_we1,
        p_ZL5K_buf_3_d1,
        p_ZL5V_buf_3_address1,
        p_ZL5V_buf_3_ce1,
        p_ZL5V_buf_3_we1,
        p_ZL5V_buf_3_d1,
        p_ZL5K_buf_4_address1,
        p_ZL5K_buf_4_ce1,
        p_ZL5K_buf_4_we1,
        p_ZL5K_buf_4_d1,
        p_ZL5V_buf_4_address1,
        p_ZL5V_buf_4_ce1,
        p_ZL5V_buf_4_we1,
        p_ZL5V_buf_4_d1,
        p_ZL5K_buf_5_address1,
        p_ZL5K_buf_5_ce1,
        p_ZL5K_buf_5_we1,
        p_ZL5K_buf_5_d1,
        p_ZL5V_buf_5_address1,
        p_ZL5V_buf_5_ce1,
        p_ZL5V_buf_5_we1,
        p_ZL5V_buf_5_d1,
        p_ZL5K_buf_6_address1,
        p_ZL5K_buf_6_ce1,
        p_ZL5K_buf_6_we1,
        p_ZL5K_buf_6_d1,
        p_ZL5V_buf_6_address1,
        p_ZL5V_buf_6_ce1,
        p_ZL5V_buf_6_we1,
        p_ZL5V_buf_6_d1,
        p_ZL5K_buf_7_address1,
        p_ZL5K_buf_7_ce1,
        p_ZL5K_buf_7_we1,
        p_ZL5K_buf_7_d1,
        p_ZL5V_buf_7_address1,
        p_ZL5V_buf_7_ce1,
        p_ZL5V_buf_7_we1,
        p_ZL5V_buf_7_d1,
        p_ZL5K_buf_8_address1,
        p_ZL5K_buf_8_ce1,
        p_ZL5K_buf_8_we1,
        p_ZL5K_buf_8_d1,
        p_ZL5V_buf_8_address1,
        p_ZL5V_buf_8_ce1,
        p_ZL5V_buf_8_we1,
        p_ZL5V_buf_8_d1,
        p_ZL5K_buf_9_address1,
        p_ZL5K_buf_9_ce1,
        p_ZL5K_buf_9_we1,
        p_ZL5K_buf_9_d1,
        p_ZL5V_buf_9_address1,
        p_ZL5V_buf_9_ce1,
        p_ZL5V_buf_9_we1,
        p_ZL5V_buf_9_d1,
        p_ZL5K_buf_10_address1,
        p_ZL5K_buf_10_ce1,
        p_ZL5K_buf_10_we1,
        p_ZL5K_buf_10_d1,
        p_ZL5V_buf_10_address1,
        p_ZL5V_buf_10_ce1,
        p_ZL5V_buf_10_we1,
        p_ZL5V_buf_10_d1,
        p_ZL5K_buf_11_address1,
        p_ZL5K_buf_11_ce1,
        p_ZL5K_buf_11_we1,
        p_ZL5K_buf_11_d1,
        p_ZL5V_buf_11_address1,
        p_ZL5V_buf_11_ce1,
        p_ZL5V_buf_11_we1,
        p_ZL5V_buf_11_d1,
        p_ZL5K_buf_12_address1,
        p_ZL5K_buf_12_ce1,
        p_ZL5K_buf_12_we1,
        p_ZL5K_buf_12_d1,
        p_ZL5V_buf_12_address1,
        p_ZL5V_buf_12_ce1,
        p_ZL5V_buf_12_we1,
        p_ZL5V_buf_12_d1,
        p_ZL5K_buf_13_address1,
        p_ZL5K_buf_13_ce1,
        p_ZL5K_buf_13_we1,
        p_ZL5K_buf_13_d1,
        p_ZL5V_buf_13_address1,
        p_ZL5V_buf_13_ce1,
        p_ZL5V_buf_13_we1,
        p_ZL5V_buf_13_d1,
        p_ZL5K_buf_14_address1,
        p_ZL5K_buf_14_ce1,
        p_ZL5K_buf_14_we1,
        p_ZL5K_buf_14_d1,
        p_ZL5V_buf_14_address1,
        p_ZL5V_buf_14_ce1,
        p_ZL5V_buf_14_we1,
        p_ZL5V_buf_14_d1,
        p_ZL5K_buf_15_address1,
        p_ZL5K_buf_15_ce1,
        p_ZL5K_buf_15_we1,
        p_ZL5K_buf_15_d1,
        p_ZL5V_buf_15_address1,
        p_ZL5V_buf_15_ce1,
        p_ZL5V_buf_15_we1,
        p_ZL5V_buf_15_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_k_0_AWVALID;
input   m_axi_gmem_k_0_AWREADY;
output  [63:0] m_axi_gmem_k_0_AWADDR;
output  [0:0] m_axi_gmem_k_0_AWID;
output  [31:0] m_axi_gmem_k_0_AWLEN;
output  [2:0] m_axi_gmem_k_0_AWSIZE;
output  [1:0] m_axi_gmem_k_0_AWBURST;
output  [1:0] m_axi_gmem_k_0_AWLOCK;
output  [3:0] m_axi_gmem_k_0_AWCACHE;
output  [2:0] m_axi_gmem_k_0_AWPROT;
output  [3:0] m_axi_gmem_k_0_AWQOS;
output  [3:0] m_axi_gmem_k_0_AWREGION;
output  [0:0] m_axi_gmem_k_0_AWUSER;
output   m_axi_gmem_k_0_WVALID;
input   m_axi_gmem_k_0_WREADY;
output  [15:0] m_axi_gmem_k_0_WDATA;
output  [1:0] m_axi_gmem_k_0_WSTRB;
output   m_axi_gmem_k_0_WLAST;
output  [0:0] m_axi_gmem_k_0_WID;
output  [0:0] m_axi_gmem_k_0_WUSER;
output   m_axi_gmem_k_0_ARVALID;
input   m_axi_gmem_k_0_ARREADY;
output  [63:0] m_axi_gmem_k_0_ARADDR;
output  [0:0] m_axi_gmem_k_0_ARID;
output  [31:0] m_axi_gmem_k_0_ARLEN;
output  [2:0] m_axi_gmem_k_0_ARSIZE;
output  [1:0] m_axi_gmem_k_0_ARBURST;
output  [1:0] m_axi_gmem_k_0_ARLOCK;
output  [3:0] m_axi_gmem_k_0_ARCACHE;
output  [2:0] m_axi_gmem_k_0_ARPROT;
output  [3:0] m_axi_gmem_k_0_ARQOS;
output  [3:0] m_axi_gmem_k_0_ARREGION;
output  [0:0] m_axi_gmem_k_0_ARUSER;
input   m_axi_gmem_k_0_RVALID;
output   m_axi_gmem_k_0_RREADY;
input  [15:0] m_axi_gmem_k_0_RDATA;
input   m_axi_gmem_k_0_RLAST;
input  [0:0] m_axi_gmem_k_0_RID;
input  [9:0] m_axi_gmem_k_0_RFIFONUM;
input  [0:0] m_axi_gmem_k_0_RUSER;
input  [1:0] m_axi_gmem_k_0_RRESP;
input   m_axi_gmem_k_0_BVALID;
output   m_axi_gmem_k_0_BREADY;
input  [1:0] m_axi_gmem_k_0_BRESP;
input  [0:0] m_axi_gmem_k_0_BID;
input  [0:0] m_axi_gmem_k_0_BUSER;
output   m_axi_gmem_v_0_AWVALID;
input   m_axi_gmem_v_0_AWREADY;
output  [63:0] m_axi_gmem_v_0_AWADDR;
output  [0:0] m_axi_gmem_v_0_AWID;
output  [31:0] m_axi_gmem_v_0_AWLEN;
output  [2:0] m_axi_gmem_v_0_AWSIZE;
output  [1:0] m_axi_gmem_v_0_AWBURST;
output  [1:0] m_axi_gmem_v_0_AWLOCK;
output  [3:0] m_axi_gmem_v_0_AWCACHE;
output  [2:0] m_axi_gmem_v_0_AWPROT;
output  [3:0] m_axi_gmem_v_0_AWQOS;
output  [3:0] m_axi_gmem_v_0_AWREGION;
output  [0:0] m_axi_gmem_v_0_AWUSER;
output   m_axi_gmem_v_0_WVALID;
input   m_axi_gmem_v_0_WREADY;
output  [15:0] m_axi_gmem_v_0_WDATA;
output  [1:0] m_axi_gmem_v_0_WSTRB;
output   m_axi_gmem_v_0_WLAST;
output  [0:0] m_axi_gmem_v_0_WID;
output  [0:0] m_axi_gmem_v_0_WUSER;
output   m_axi_gmem_v_0_ARVALID;
input   m_axi_gmem_v_0_ARREADY;
output  [63:0] m_axi_gmem_v_0_ARADDR;
output  [0:0] m_axi_gmem_v_0_ARID;
output  [31:0] m_axi_gmem_v_0_ARLEN;
output  [2:0] m_axi_gmem_v_0_ARSIZE;
output  [1:0] m_axi_gmem_v_0_ARBURST;
output  [1:0] m_axi_gmem_v_0_ARLOCK;
output  [3:0] m_axi_gmem_v_0_ARCACHE;
output  [2:0] m_axi_gmem_v_0_ARPROT;
output  [3:0] m_axi_gmem_v_0_ARQOS;
output  [3:0] m_axi_gmem_v_0_ARREGION;
output  [0:0] m_axi_gmem_v_0_ARUSER;
input   m_axi_gmem_v_0_RVALID;
output   m_axi_gmem_v_0_RREADY;
input  [15:0] m_axi_gmem_v_0_RDATA;
input   m_axi_gmem_v_0_RLAST;
input  [0:0] m_axi_gmem_v_0_RID;
input  [9:0] m_axi_gmem_v_0_RFIFONUM;
input  [0:0] m_axi_gmem_v_0_RUSER;
input  [1:0] m_axi_gmem_v_0_RRESP;
input   m_axi_gmem_v_0_BVALID;
output   m_axi_gmem_v_0_BREADY;
input  [1:0] m_axi_gmem_v_0_BRESP;
input  [0:0] m_axi_gmem_v_0_BID;
input  [0:0] m_axi_gmem_v_0_BUSER;
input  [9:0] zext_ln90;
input  [63:0] V;
input  [63:0] K;
output  [9:0] p_ZL5K_buf_0_address1;
output   p_ZL5K_buf_0_ce1;
output   p_ZL5K_buf_0_we1;
output  [15:0] p_ZL5K_buf_0_d1;
output  [9:0] p_ZL5V_buf_0_address1;
output   p_ZL5V_buf_0_ce1;
output   p_ZL5V_buf_0_we1;
output  [15:0] p_ZL5V_buf_0_d1;
output  [9:0] p_ZL5K_buf_1_address1;
output   p_ZL5K_buf_1_ce1;
output   p_ZL5K_buf_1_we1;
output  [15:0] p_ZL5K_buf_1_d1;
output  [9:0] p_ZL5V_buf_1_address1;
output   p_ZL5V_buf_1_ce1;
output   p_ZL5V_buf_1_we1;
output  [15:0] p_ZL5V_buf_1_d1;
output  [9:0] p_ZL5K_buf_2_address1;
output   p_ZL5K_buf_2_ce1;
output   p_ZL5K_buf_2_we1;
output  [15:0] p_ZL5K_buf_2_d1;
output  [9:0] p_ZL5V_buf_2_address1;
output   p_ZL5V_buf_2_ce1;
output   p_ZL5V_buf_2_we1;
output  [15:0] p_ZL5V_buf_2_d1;
output  [9:0] p_ZL5K_buf_3_address1;
output   p_ZL5K_buf_3_ce1;
output   p_ZL5K_buf_3_we1;
output  [15:0] p_ZL5K_buf_3_d1;
output  [9:0] p_ZL5V_buf_3_address1;
output   p_ZL5V_buf_3_ce1;
output   p_ZL5V_buf_3_we1;
output  [15:0] p_ZL5V_buf_3_d1;
output  [9:0] p_ZL5K_buf_4_address1;
output   p_ZL5K_buf_4_ce1;
output   p_ZL5K_buf_4_we1;
output  [15:0] p_ZL5K_buf_4_d1;
output  [9:0] p_ZL5V_buf_4_address1;
output   p_ZL5V_buf_4_ce1;
output   p_ZL5V_buf_4_we1;
output  [15:0] p_ZL5V_buf_4_d1;
output  [9:0] p_ZL5K_buf_5_address1;
output   p_ZL5K_buf_5_ce1;
output   p_ZL5K_buf_5_we1;
output  [15:0] p_ZL5K_buf_5_d1;
output  [9:0] p_ZL5V_buf_5_address1;
output   p_ZL5V_buf_5_ce1;
output   p_ZL5V_buf_5_we1;
output  [15:0] p_ZL5V_buf_5_d1;
output  [9:0] p_ZL5K_buf_6_address1;
output   p_ZL5K_buf_6_ce1;
output   p_ZL5K_buf_6_we1;
output  [15:0] p_ZL5K_buf_6_d1;
output  [9:0] p_ZL5V_buf_6_address1;
output   p_ZL5V_buf_6_ce1;
output   p_ZL5V_buf_6_we1;
output  [15:0] p_ZL5V_buf_6_d1;
output  [9:0] p_ZL5K_buf_7_address1;
output   p_ZL5K_buf_7_ce1;
output   p_ZL5K_buf_7_we1;
output  [15:0] p_ZL5K_buf_7_d1;
output  [9:0] p_ZL5V_buf_7_address1;
output   p_ZL5V_buf_7_ce1;
output   p_ZL5V_buf_7_we1;
output  [15:0] p_ZL5V_buf_7_d1;
output  [9:0] p_ZL5K_buf_8_address1;
output   p_ZL5K_buf_8_ce1;
output   p_ZL5K_buf_8_we1;
output  [15:0] p_ZL5K_buf_8_d1;
output  [9:0] p_ZL5V_buf_8_address1;
output   p_ZL5V_buf_8_ce1;
output   p_ZL5V_buf_8_we1;
output  [15:0] p_ZL5V_buf_8_d1;
output  [9:0] p_ZL5K_buf_9_address1;
output   p_ZL5K_buf_9_ce1;
output   p_ZL5K_buf_9_we1;
output  [15:0] p_ZL5K_buf_9_d1;
output  [9:0] p_ZL5V_buf_9_address1;
output   p_ZL5V_buf_9_ce1;
output   p_ZL5V_buf_9_we1;
output  [15:0] p_ZL5V_buf_9_d1;
output  [9:0] p_ZL5K_buf_10_address1;
output   p_ZL5K_buf_10_ce1;
output   p_ZL5K_buf_10_we1;
output  [15:0] p_ZL5K_buf_10_d1;
output  [9:0] p_ZL5V_buf_10_address1;
output   p_ZL5V_buf_10_ce1;
output   p_ZL5V_buf_10_we1;
output  [15:0] p_ZL5V_buf_10_d1;
output  [9:0] p_ZL5K_buf_11_address1;
output   p_ZL5K_buf_11_ce1;
output   p_ZL5K_buf_11_we1;
output  [15:0] p_ZL5K_buf_11_d1;
output  [9:0] p_ZL5V_buf_11_address1;
output   p_ZL5V_buf_11_ce1;
output   p_ZL5V_buf_11_we1;
output  [15:0] p_ZL5V_buf_11_d1;
output  [9:0] p_ZL5K_buf_12_address1;
output   p_ZL5K_buf_12_ce1;
output   p_ZL5K_buf_12_we1;
output  [15:0] p_ZL5K_buf_12_d1;
output  [9:0] p_ZL5V_buf_12_address1;
output   p_ZL5V_buf_12_ce1;
output   p_ZL5V_buf_12_we1;
output  [15:0] p_ZL5V_buf_12_d1;
output  [9:0] p_ZL5K_buf_13_address1;
output   p_ZL5K_buf_13_ce1;
output   p_ZL5K_buf_13_we1;
output  [15:0] p_ZL5K_buf_13_d1;
output  [9:0] p_ZL5V_buf_13_address1;
output   p_ZL5V_buf_13_ce1;
output   p_ZL5V_buf_13_we1;
output  [15:0] p_ZL5V_buf_13_d1;
output  [9:0] p_ZL5K_buf_14_address1;
output   p_ZL5K_buf_14_ce1;
output   p_ZL5K_buf_14_we1;
output  [15:0] p_ZL5K_buf_14_d1;
output  [9:0] p_ZL5V_buf_14_address1;
output   p_ZL5V_buf_14_ce1;
output   p_ZL5V_buf_14_we1;
output  [15:0] p_ZL5V_buf_14_d1;
output  [9:0] p_ZL5K_buf_15_address1;
output   p_ZL5K_buf_15_ce1;
output   p_ZL5K_buf_15_we1;
output  [15:0] p_ZL5K_buf_15_d1;
output  [9:0] p_ZL5V_buf_15_address1;
output   p_ZL5V_buf_15_ce1;
output   p_ZL5V_buf_15_we1;
output  [15:0] p_ZL5V_buf_15_d1;

reg ap_idle;
reg m_axi_gmem_k_0_ARVALID;
reg m_axi_gmem_k_0_RREADY;
reg m_axi_gmem_v_0_ARVALID;
reg m_axi_gmem_v_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_1107;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_state2_io_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
wire   [0:0] icmp_ln90_fu_818_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_v_blk_n_R;
wire    ap_block_pp0_stage0_grp4;
reg    gmem_v_blk_n_AR;
wire    ap_block_pp0_stage0_grp2;
reg    gmem_k_blk_n_R;
wire    ap_block_pp0_stage0_grp3;
reg    gmem_k_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln90_1_fu_856_p3;
reg   [7:0] select_ln90_1_reg_1102;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter1_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter2_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter3_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter4_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter5_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter6_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter7_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter8_reg;
reg   [7:0] select_ln90_1_reg_1102_pp0_iter9_reg;
wire   [0:0] first_iter_0_fu_864_p2;
reg   [63:0] gmem_k_addr_reg_1111;
reg   [63:0] gmem_v_addr_reg_1117;
wire   [3:0] trunc_ln91_fu_966_p1;
reg   [3:0] trunc_ln91_reg_1123;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter1_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter2_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter3_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter4_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter5_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter6_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter7_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter8_reg;
reg   [3:0] trunc_ln91_reg_1123_pp0_iter9_reg;
reg   [1:0] lshr_ln_reg_1127;
reg   [1:0] lshr_ln_reg_1127_pp0_iter1_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter2_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter3_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter4_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter5_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter6_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter7_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter8_reg;
reg   [1:0] lshr_ln_reg_1127_pp0_iter9_reg;
reg   [15:0] gmem_k_addr_read_reg_1132;
reg    ap_block_pp0_stage0_11001_grp3;
reg   [15:0] gmem_v_addr_read_reg_1152;
reg    ap_block_pp0_stage0_11001_grp4;
wire   [63:0] zext_ln93_fu_1041_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln91_fu_936_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln91_1_fu_956_p1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [6:0] j_fu_198;
wire   [6:0] add_ln91_fu_1014_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [7:0] i_fu_202;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [13:0] indvar_flatten_fu_206;
wire   [13:0] add_ln90_4_fu_824_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten_load;
reg    p_ZL5K_buf_14_we1_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    p_ZL5K_buf_14_ce1_local;
reg    p_ZL5V_buf_14_we1_local;
reg    p_ZL5V_buf_14_ce1_local;
reg    p_ZL5K_buf_13_we1_local;
reg    p_ZL5K_buf_13_ce1_local;
reg    p_ZL5V_buf_13_we1_local;
reg    p_ZL5V_buf_13_ce1_local;
reg    p_ZL5K_buf_12_we1_local;
reg    p_ZL5K_buf_12_ce1_local;
reg    p_ZL5V_buf_12_we1_local;
reg    p_ZL5V_buf_12_ce1_local;
reg    p_ZL5K_buf_11_we1_local;
reg    p_ZL5K_buf_11_ce1_local;
reg    p_ZL5V_buf_11_we1_local;
reg    p_ZL5V_buf_11_ce1_local;
reg    p_ZL5K_buf_10_we1_local;
reg    p_ZL5K_buf_10_ce1_local;
reg    p_ZL5V_buf_10_we1_local;
reg    p_ZL5V_buf_10_ce1_local;
reg    p_ZL5K_buf_9_we1_local;
reg    p_ZL5K_buf_9_ce1_local;
reg    p_ZL5V_buf_9_we1_local;
reg    p_ZL5V_buf_9_ce1_local;
reg    p_ZL5K_buf_8_we1_local;
reg    p_ZL5K_buf_8_ce1_local;
reg    p_ZL5V_buf_8_we1_local;
reg    p_ZL5V_buf_8_ce1_local;
reg    p_ZL5K_buf_7_we1_local;
reg    p_ZL5K_buf_7_ce1_local;
reg    p_ZL5V_buf_7_we1_local;
reg    p_ZL5V_buf_7_ce1_local;
reg    p_ZL5K_buf_6_we1_local;
reg    p_ZL5K_buf_6_ce1_local;
reg    p_ZL5V_buf_6_we1_local;
reg    p_ZL5V_buf_6_ce1_local;
reg    p_ZL5K_buf_5_we1_local;
reg    p_ZL5K_buf_5_ce1_local;
reg    p_ZL5V_buf_5_we1_local;
reg    p_ZL5V_buf_5_ce1_local;
reg    p_ZL5K_buf_4_we1_local;
reg    p_ZL5K_buf_4_ce1_local;
reg    p_ZL5V_buf_4_we1_local;
reg    p_ZL5V_buf_4_ce1_local;
reg    p_ZL5K_buf_3_we1_local;
reg    p_ZL5K_buf_3_ce1_local;
reg    p_ZL5V_buf_3_we1_local;
reg    p_ZL5V_buf_3_ce1_local;
reg    p_ZL5K_buf_2_we1_local;
reg    p_ZL5K_buf_2_ce1_local;
reg    p_ZL5V_buf_2_we1_local;
reg    p_ZL5V_buf_2_ce1_local;
reg    p_ZL5K_buf_1_we1_local;
reg    p_ZL5K_buf_1_ce1_local;
reg    p_ZL5V_buf_1_we1_local;
reg    p_ZL5V_buf_1_ce1_local;
reg    p_ZL5K_buf_0_we1_local;
reg    p_ZL5K_buf_0_ce1_local;
reg    p_ZL5V_buf_0_we1_local;
reg    p_ZL5V_buf_0_ce1_local;
reg    p_ZL5K_buf_15_we1_local;
reg    p_ZL5K_buf_15_ce1_local;
reg    p_ZL5V_buf_15_we1_local;
reg    p_ZL5V_buf_15_ce1_local;
wire   [0:0] icmp_ln91_fu_842_p2;
wire   [7:0] add_ln90_3_fu_836_p2;
wire   [6:0] select_ln90_fu_848_p3;
wire   [15:0] tmp_fu_878_p3;
wire   [17:0] p_shl_fu_870_p3;
wire   [17:0] zext_ln90_1_fu_886_p1;
wire   [17:0] sub_ln90_fu_890_p2;
wire   [17:0] zext_ln90_cast_fu_796_p1;
wire   [17:0] add_ln90_fu_896_p2;
wire   [18:0] shl_ln2_fu_902_p3;
wire   [63:0] zext_ln90_2_fu_910_p1;
wire   [63:0] add_ln90_2_fu_920_p2;
wire   [62:0] trunc_ln_fu_926_p4;
wire   [63:0] add_ln90_1_fu_914_p2;
wire   [62:0] trunc_ln91_1_fu_946_p4;
wire   [9:0] tmp_s_fu_1035_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 j_fu_198 = 7'd0;
#0 i_fu_202 = 8'd0;
#0 indvar_flatten_fu_206 = 14'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

mhsa_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
            ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
            ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_818_p2 == 1'd0))) begin
            i_fu_202 <= select_ln90_1_fu_856_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_202 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_818_p2 == 1'd0))) begin
            indvar_flatten_fu_206 <= add_ln90_4_fu_824_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_206 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_818_p2 == 1'd0))) begin
            j_fu_198 <= add_ln91_fu_1014_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_198 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_1107 <= first_iter_0_fu_864_p2;
        gmem_k_addr_reg_1111 <= sext_ln91_fu_936_p1;
        gmem_v_addr_reg_1117 <= sext_ln91_1_fu_956_p1;
        lshr_ln_reg_1127 <= {{select_ln90_fu_848_p3[5:4]}};
        lshr_ln_reg_1127_pp0_iter1_reg <= lshr_ln_reg_1127;
        select_ln90_1_reg_1102 <= select_ln90_1_fu_856_p3;
        select_ln90_1_reg_1102_pp0_iter1_reg <= select_ln90_1_reg_1102;
        trunc_ln91_reg_1123 <= trunc_ln91_fu_966_p1;
        trunc_ln91_reg_1123_pp0_iter1_reg <= trunc_ln91_reg_1123;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        lshr_ln_reg_1127_pp0_iter2_reg <= lshr_ln_reg_1127_pp0_iter1_reg;
        lshr_ln_reg_1127_pp0_iter3_reg <= lshr_ln_reg_1127_pp0_iter2_reg;
        lshr_ln_reg_1127_pp0_iter4_reg <= lshr_ln_reg_1127_pp0_iter3_reg;
        lshr_ln_reg_1127_pp0_iter5_reg <= lshr_ln_reg_1127_pp0_iter4_reg;
        lshr_ln_reg_1127_pp0_iter6_reg <= lshr_ln_reg_1127_pp0_iter5_reg;
        lshr_ln_reg_1127_pp0_iter7_reg <= lshr_ln_reg_1127_pp0_iter6_reg;
        lshr_ln_reg_1127_pp0_iter8_reg <= lshr_ln_reg_1127_pp0_iter7_reg;
        lshr_ln_reg_1127_pp0_iter9_reg <= lshr_ln_reg_1127_pp0_iter8_reg;
        select_ln90_1_reg_1102_pp0_iter2_reg <= select_ln90_1_reg_1102_pp0_iter1_reg;
        select_ln90_1_reg_1102_pp0_iter3_reg <= select_ln90_1_reg_1102_pp0_iter2_reg;
        select_ln90_1_reg_1102_pp0_iter4_reg <= select_ln90_1_reg_1102_pp0_iter3_reg;
        select_ln90_1_reg_1102_pp0_iter5_reg <= select_ln90_1_reg_1102_pp0_iter4_reg;
        select_ln90_1_reg_1102_pp0_iter6_reg <= select_ln90_1_reg_1102_pp0_iter5_reg;
        select_ln90_1_reg_1102_pp0_iter7_reg <= select_ln90_1_reg_1102_pp0_iter6_reg;
        select_ln90_1_reg_1102_pp0_iter8_reg <= select_ln90_1_reg_1102_pp0_iter7_reg;
        select_ln90_1_reg_1102_pp0_iter9_reg <= select_ln90_1_reg_1102_pp0_iter8_reg;
        trunc_ln91_reg_1123_pp0_iter2_reg <= trunc_ln91_reg_1123_pp0_iter1_reg;
        trunc_ln91_reg_1123_pp0_iter3_reg <= trunc_ln91_reg_1123_pp0_iter2_reg;
        trunc_ln91_reg_1123_pp0_iter4_reg <= trunc_ln91_reg_1123_pp0_iter3_reg;
        trunc_ln91_reg_1123_pp0_iter5_reg <= trunc_ln91_reg_1123_pp0_iter4_reg;
        trunc_ln91_reg_1123_pp0_iter6_reg <= trunc_ln91_reg_1123_pp0_iter5_reg;
        trunc_ln91_reg_1123_pp0_iter7_reg <= trunc_ln91_reg_1123_pp0_iter6_reg;
        trunc_ln91_reg_1123_pp0_iter8_reg <= trunc_ln91_reg_1123_pp0_iter7_reg;
        trunc_ln91_reg_1123_pp0_iter9_reg <= trunc_ln91_reg_1123_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        gmem_k_addr_read_reg_1132 <= m_axi_gmem_k_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        gmem_v_addr_read_reg_1152 <= m_axi_gmem_v_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_818_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_202;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_206;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_198;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (first_iter_0_reg_1107 == 1'd1))) begin
        gmem_k_blk_n_AR = m_axi_gmem_k_0_ARREADY;
    end else begin
        gmem_k_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        gmem_k_blk_n_R = m_axi_gmem_k_0_RVALID;
    end else begin
        gmem_k_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (first_iter_0_reg_1107 == 1'd1))) begin
        gmem_v_blk_n_AR = m_axi_gmem_v_0_ARREADY;
    end else begin
        gmem_v_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        gmem_v_blk_n_R = m_axi_gmem_v_0_RVALID;
    end else begin
        gmem_v_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (first_iter_0_reg_1107 == 1'd1))) begin
        m_axi_gmem_k_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_k_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        m_axi_gmem_k_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_k_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (first_iter_0_reg_1107 == 1'd1))) begin
        m_axi_gmem_v_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_v_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        m_axi_gmem_v_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_v_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_0_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_0_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_10_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd10) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_10_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_11_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd11) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_11_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_12_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd12) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_12_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_13_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd13) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_13_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_14_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd14) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_14_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_15_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd15) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_15_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_1_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_1_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_2_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd2) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_2_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_3_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd3) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_3_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_4_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd4) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_4_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_5_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd5) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_5_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_6_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd6) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_6_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_7_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd7) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_7_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_8_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd8) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_8_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_9_ce1_local = 1'b1;
    end else begin
        p_ZL5K_buf_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd9) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5K_buf_9_we1_local = 1'b1;
    end else begin
        p_ZL5K_buf_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_0_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_0_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_10_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd10) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_10_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_11_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd11) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_11_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_12_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd12) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_12_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_13_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd13) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_13_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_14_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd14) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_14_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_15_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd15) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_15_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_1_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_1_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_2_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd2) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_2_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_3_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd3) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_3_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_4_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd4) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_4_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_5_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd5) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_5_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_6_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd6) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_6_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_7_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd7) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_7_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_8_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd8) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_8_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_9_ce1_local = 1'b1;
    end else begin
        p_ZL5V_buf_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln91_reg_1123_pp0_iter9_reg == 4'd9) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL5V_buf_9_we1_local = 1'b1;
    end else begin
        p_ZL5V_buf_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_1_fu_914_p2 = (zext_ln90_2_fu_910_p1 + V);

assign add_ln90_2_fu_920_p2 = (zext_ln90_2_fu_910_p1 + K);

assign add_ln90_3_fu_836_p2 = (ap_sig_allocacmp_i_load + 8'd1);

assign add_ln90_4_fu_824_p2 = (ap_sig_allocacmp_indvar_flatten_load + 14'd1);

assign add_ln90_fu_896_p2 = (sub_ln90_fu_890_p2 + zext_ln90_cast_fu_796_p1);

assign add_ln91_fu_1014_p2 = (select_ln90_fu_848_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_v_0_RVALID == 1'b0)) | ((m_axi_gmem_k_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((m_axi_gmem_k_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_v_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_v_0_RVALID == 1'b0)) | ((m_axi_gmem_k_0_RVALID == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg)) | ((1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((m_axi_gmem_k_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (m_axi_gmem_v_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((m_axi_gmem_k_0_ARREADY == 1'b0) & (first_iter_0_reg_1107 == 1'd1));
end

always @ (*) begin
    ap_block_state2_io_grp2 = ((first_iter_0_reg_1107 == 1'd1) & (m_axi_gmem_v_0_ARREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign first_iter_0_fu_864_p2 = ((select_ln90_fu_848_p3 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_818_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 14'd12608) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_842_p2 = ((ap_sig_allocacmp_j_load == 7'd64) ? 1'b1 : 1'b0);

assign m_axi_gmem_k_0_ARADDR = gmem_k_addr_reg_1111;

assign m_axi_gmem_k_0_ARBURST = 2'd0;

assign m_axi_gmem_k_0_ARCACHE = 4'd0;

assign m_axi_gmem_k_0_ARID = 1'd0;

assign m_axi_gmem_k_0_ARLEN = 64'd64;

assign m_axi_gmem_k_0_ARLOCK = 2'd0;

assign m_axi_gmem_k_0_ARPROT = 3'd0;

assign m_axi_gmem_k_0_ARQOS = 4'd0;

assign m_axi_gmem_k_0_ARREGION = 4'd0;

assign m_axi_gmem_k_0_ARSIZE = 3'd0;

assign m_axi_gmem_k_0_ARUSER = 1'd0;

assign m_axi_gmem_k_0_AWADDR = 64'd0;

assign m_axi_gmem_k_0_AWBURST = 2'd0;

assign m_axi_gmem_k_0_AWCACHE = 4'd0;

assign m_axi_gmem_k_0_AWID = 1'd0;

assign m_axi_gmem_k_0_AWLEN = 32'd0;

assign m_axi_gmem_k_0_AWLOCK = 2'd0;

assign m_axi_gmem_k_0_AWPROT = 3'd0;

assign m_axi_gmem_k_0_AWQOS = 4'd0;

assign m_axi_gmem_k_0_AWREGION = 4'd0;

assign m_axi_gmem_k_0_AWSIZE = 3'd0;

assign m_axi_gmem_k_0_AWUSER = 1'd0;

assign m_axi_gmem_k_0_AWVALID = 1'b0;

assign m_axi_gmem_k_0_BREADY = 1'b0;

assign m_axi_gmem_k_0_WDATA = 16'd0;

assign m_axi_gmem_k_0_WID = 1'd0;

assign m_axi_gmem_k_0_WLAST = 1'b0;

assign m_axi_gmem_k_0_WSTRB = 2'd0;

assign m_axi_gmem_k_0_WUSER = 1'd0;

assign m_axi_gmem_k_0_WVALID = 1'b0;

assign m_axi_gmem_v_0_ARADDR = gmem_v_addr_reg_1117;

assign m_axi_gmem_v_0_ARBURST = 2'd0;

assign m_axi_gmem_v_0_ARCACHE = 4'd0;

assign m_axi_gmem_v_0_ARID = 1'd0;

assign m_axi_gmem_v_0_ARLEN = 64'd64;

assign m_axi_gmem_v_0_ARLOCK = 2'd0;

assign m_axi_gmem_v_0_ARPROT = 3'd0;

assign m_axi_gmem_v_0_ARQOS = 4'd0;

assign m_axi_gmem_v_0_ARREGION = 4'd0;

assign m_axi_gmem_v_0_ARSIZE = 3'd0;

assign m_axi_gmem_v_0_ARUSER = 1'd0;

assign m_axi_gmem_v_0_AWADDR = 64'd0;

assign m_axi_gmem_v_0_AWBURST = 2'd0;

assign m_axi_gmem_v_0_AWCACHE = 4'd0;

assign m_axi_gmem_v_0_AWID = 1'd0;

assign m_axi_gmem_v_0_AWLEN = 32'd0;

assign m_axi_gmem_v_0_AWLOCK = 2'd0;

assign m_axi_gmem_v_0_AWPROT = 3'd0;

assign m_axi_gmem_v_0_AWQOS = 4'd0;

assign m_axi_gmem_v_0_AWREGION = 4'd0;

assign m_axi_gmem_v_0_AWSIZE = 3'd0;

assign m_axi_gmem_v_0_AWUSER = 1'd0;

assign m_axi_gmem_v_0_AWVALID = 1'b0;

assign m_axi_gmem_v_0_BREADY = 1'b0;

assign m_axi_gmem_v_0_WDATA = 16'd0;

assign m_axi_gmem_v_0_WID = 1'd0;

assign m_axi_gmem_v_0_WLAST = 1'b0;

assign m_axi_gmem_v_0_WSTRB = 2'd0;

assign m_axi_gmem_v_0_WUSER = 1'd0;

assign m_axi_gmem_v_0_WVALID = 1'b0;

assign p_ZL5K_buf_0_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_0_ce1 = p_ZL5K_buf_0_ce1_local;

assign p_ZL5K_buf_0_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_0_we1 = p_ZL5K_buf_0_we1_local;

assign p_ZL5K_buf_10_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_10_ce1 = p_ZL5K_buf_10_ce1_local;

assign p_ZL5K_buf_10_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_10_we1 = p_ZL5K_buf_10_we1_local;

assign p_ZL5K_buf_11_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_11_ce1 = p_ZL5K_buf_11_ce1_local;

assign p_ZL5K_buf_11_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_11_we1 = p_ZL5K_buf_11_we1_local;

assign p_ZL5K_buf_12_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_12_ce1 = p_ZL5K_buf_12_ce1_local;

assign p_ZL5K_buf_12_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_12_we1 = p_ZL5K_buf_12_we1_local;

assign p_ZL5K_buf_13_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_13_ce1 = p_ZL5K_buf_13_ce1_local;

assign p_ZL5K_buf_13_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_13_we1 = p_ZL5K_buf_13_we1_local;

assign p_ZL5K_buf_14_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_14_ce1 = p_ZL5K_buf_14_ce1_local;

assign p_ZL5K_buf_14_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_14_we1 = p_ZL5K_buf_14_we1_local;

assign p_ZL5K_buf_15_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_15_ce1 = p_ZL5K_buf_15_ce1_local;

assign p_ZL5K_buf_15_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_15_we1 = p_ZL5K_buf_15_we1_local;

assign p_ZL5K_buf_1_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_1_ce1 = p_ZL5K_buf_1_ce1_local;

assign p_ZL5K_buf_1_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_1_we1 = p_ZL5K_buf_1_we1_local;

assign p_ZL5K_buf_2_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_2_ce1 = p_ZL5K_buf_2_ce1_local;

assign p_ZL5K_buf_2_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_2_we1 = p_ZL5K_buf_2_we1_local;

assign p_ZL5K_buf_3_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_3_ce1 = p_ZL5K_buf_3_ce1_local;

assign p_ZL5K_buf_3_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_3_we1 = p_ZL5K_buf_3_we1_local;

assign p_ZL5K_buf_4_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_4_ce1 = p_ZL5K_buf_4_ce1_local;

assign p_ZL5K_buf_4_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_4_we1 = p_ZL5K_buf_4_we1_local;

assign p_ZL5K_buf_5_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_5_ce1 = p_ZL5K_buf_5_ce1_local;

assign p_ZL5K_buf_5_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_5_we1 = p_ZL5K_buf_5_we1_local;

assign p_ZL5K_buf_6_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_6_ce1 = p_ZL5K_buf_6_ce1_local;

assign p_ZL5K_buf_6_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_6_we1 = p_ZL5K_buf_6_we1_local;

assign p_ZL5K_buf_7_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_7_ce1 = p_ZL5K_buf_7_ce1_local;

assign p_ZL5K_buf_7_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_7_we1 = p_ZL5K_buf_7_we1_local;

assign p_ZL5K_buf_8_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_8_ce1 = p_ZL5K_buf_8_ce1_local;

assign p_ZL5K_buf_8_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_8_we1 = p_ZL5K_buf_8_we1_local;

assign p_ZL5K_buf_9_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5K_buf_9_ce1 = p_ZL5K_buf_9_ce1_local;

assign p_ZL5K_buf_9_d1 = gmem_k_addr_read_reg_1132;

assign p_ZL5K_buf_9_we1 = p_ZL5K_buf_9_we1_local;

assign p_ZL5V_buf_0_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_0_ce1 = p_ZL5V_buf_0_ce1_local;

assign p_ZL5V_buf_0_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_0_we1 = p_ZL5V_buf_0_we1_local;

assign p_ZL5V_buf_10_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_10_ce1 = p_ZL5V_buf_10_ce1_local;

assign p_ZL5V_buf_10_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_10_we1 = p_ZL5V_buf_10_we1_local;

assign p_ZL5V_buf_11_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_11_ce1 = p_ZL5V_buf_11_ce1_local;

assign p_ZL5V_buf_11_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_11_we1 = p_ZL5V_buf_11_we1_local;

assign p_ZL5V_buf_12_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_12_ce1 = p_ZL5V_buf_12_ce1_local;

assign p_ZL5V_buf_12_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_12_we1 = p_ZL5V_buf_12_we1_local;

assign p_ZL5V_buf_13_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_13_ce1 = p_ZL5V_buf_13_ce1_local;

assign p_ZL5V_buf_13_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_13_we1 = p_ZL5V_buf_13_we1_local;

assign p_ZL5V_buf_14_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_14_ce1 = p_ZL5V_buf_14_ce1_local;

assign p_ZL5V_buf_14_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_14_we1 = p_ZL5V_buf_14_we1_local;

assign p_ZL5V_buf_15_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_15_ce1 = p_ZL5V_buf_15_ce1_local;

assign p_ZL5V_buf_15_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_15_we1 = p_ZL5V_buf_15_we1_local;

assign p_ZL5V_buf_1_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_1_ce1 = p_ZL5V_buf_1_ce1_local;

assign p_ZL5V_buf_1_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_1_we1 = p_ZL5V_buf_1_we1_local;

assign p_ZL5V_buf_2_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_2_ce1 = p_ZL5V_buf_2_ce1_local;

assign p_ZL5V_buf_2_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_2_we1 = p_ZL5V_buf_2_we1_local;

assign p_ZL5V_buf_3_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_3_ce1 = p_ZL5V_buf_3_ce1_local;

assign p_ZL5V_buf_3_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_3_we1 = p_ZL5V_buf_3_we1_local;

assign p_ZL5V_buf_4_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_4_ce1 = p_ZL5V_buf_4_ce1_local;

assign p_ZL5V_buf_4_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_4_we1 = p_ZL5V_buf_4_we1_local;

assign p_ZL5V_buf_5_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_5_ce1 = p_ZL5V_buf_5_ce1_local;

assign p_ZL5V_buf_5_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_5_we1 = p_ZL5V_buf_5_we1_local;

assign p_ZL5V_buf_6_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_6_ce1 = p_ZL5V_buf_6_ce1_local;

assign p_ZL5V_buf_6_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_6_we1 = p_ZL5V_buf_6_we1_local;

assign p_ZL5V_buf_7_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_7_ce1 = p_ZL5V_buf_7_ce1_local;

assign p_ZL5V_buf_7_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_7_we1 = p_ZL5V_buf_7_we1_local;

assign p_ZL5V_buf_8_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_8_ce1 = p_ZL5V_buf_8_ce1_local;

assign p_ZL5V_buf_8_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_8_we1 = p_ZL5V_buf_8_we1_local;

assign p_ZL5V_buf_9_address1 = zext_ln93_fu_1041_p1;

assign p_ZL5V_buf_9_ce1 = p_ZL5V_buf_9_ce1_local;

assign p_ZL5V_buf_9_d1 = gmem_v_addr_read_reg_1152;

assign p_ZL5V_buf_9_we1 = p_ZL5V_buf_9_we1_local;

assign p_shl_fu_870_p3 = {{select_ln90_1_fu_856_p3}, {10'd0}};

assign select_ln90_1_fu_856_p3 = ((icmp_ln91_fu_842_p2[0:0] == 1'b1) ? add_ln90_3_fu_836_p2 : ap_sig_allocacmp_i_load);

assign select_ln90_fu_848_p3 = ((icmp_ln91_fu_842_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign sext_ln91_1_fu_956_p1 = $signed(trunc_ln91_1_fu_946_p4);

assign sext_ln91_fu_936_p1 = $signed(trunc_ln_fu_926_p4);

assign shl_ln2_fu_902_p3 = {{add_ln90_fu_896_p2}, {1'd0}};

assign sub_ln90_fu_890_p2 = (p_shl_fu_870_p3 - zext_ln90_1_fu_886_p1);

assign tmp_fu_878_p3 = {{select_ln90_1_fu_856_p3}, {8'd0}};

assign tmp_s_fu_1035_p3 = {{select_ln90_1_reg_1102_pp0_iter9_reg}, {lshr_ln_reg_1127_pp0_iter9_reg}};

assign trunc_ln91_1_fu_946_p4 = {{add_ln90_1_fu_914_p2[63:1]}};

assign trunc_ln91_fu_966_p1 = select_ln90_fu_848_p3[3:0];

assign trunc_ln_fu_926_p4 = {{add_ln90_2_fu_920_p2[63:1]}};

assign zext_ln90_1_fu_886_p1 = tmp_fu_878_p3;

assign zext_ln90_2_fu_910_p1 = shl_ln2_fu_902_p3;

assign zext_ln90_cast_fu_796_p1 = zext_ln90;

assign zext_ln93_fu_1041_p1 = tmp_s_fu_1035_p3;

endmodule //mhsa_top_mhsa_top_Pipeline_load_kv_VITIS_LOOP_91_1
