// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mhsa_top_mhsa_top_Pipeline_store_o (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_o_0_AWVALID,
        m_axi_gmem_o_0_AWREADY,
        m_axi_gmem_o_0_AWADDR,
        m_axi_gmem_o_0_AWID,
        m_axi_gmem_o_0_AWLEN,
        m_axi_gmem_o_0_AWSIZE,
        m_axi_gmem_o_0_AWBURST,
        m_axi_gmem_o_0_AWLOCK,
        m_axi_gmem_o_0_AWCACHE,
        m_axi_gmem_o_0_AWPROT,
        m_axi_gmem_o_0_AWQOS,
        m_axi_gmem_o_0_AWREGION,
        m_axi_gmem_o_0_AWUSER,
        m_axi_gmem_o_0_WVALID,
        m_axi_gmem_o_0_WREADY,
        m_axi_gmem_o_0_WDATA,
        m_axi_gmem_o_0_WSTRB,
        m_axi_gmem_o_0_WLAST,
        m_axi_gmem_o_0_WID,
        m_axi_gmem_o_0_WUSER,
        m_axi_gmem_o_0_ARVALID,
        m_axi_gmem_o_0_ARREADY,
        m_axi_gmem_o_0_ARADDR,
        m_axi_gmem_o_0_ARID,
        m_axi_gmem_o_0_ARLEN,
        m_axi_gmem_o_0_ARSIZE,
        m_axi_gmem_o_0_ARBURST,
        m_axi_gmem_o_0_ARLOCK,
        m_axi_gmem_o_0_ARCACHE,
        m_axi_gmem_o_0_ARPROT,
        m_axi_gmem_o_0_ARQOS,
        m_axi_gmem_o_0_ARREGION,
        m_axi_gmem_o_0_ARUSER,
        m_axi_gmem_o_0_RVALID,
        m_axi_gmem_o_0_RREADY,
        m_axi_gmem_o_0_RDATA,
        m_axi_gmem_o_0_RLAST,
        m_axi_gmem_o_0_RID,
        m_axi_gmem_o_0_RFIFONUM,
        m_axi_gmem_o_0_RUSER,
        m_axi_gmem_o_0_RRESP,
        m_axi_gmem_o_0_BVALID,
        m_axi_gmem_o_0_BREADY,
        m_axi_gmem_o_0_BRESP,
        m_axi_gmem_o_0_BID,
        m_axi_gmem_o_0_BUSER,
        sext_ln107,
        O_row_address0,
        O_row_ce0,
        O_row_q0,
        O_row_1_address0,
        O_row_1_ce0,
        O_row_1_q0,
        O_row_2_address0,
        O_row_2_ce0,
        O_row_2_q0,
        O_row_3_address0,
        O_row_3_ce0,
        O_row_3_q0,
        O_row_4_address0,
        O_row_4_ce0,
        O_row_4_q0,
        O_row_5_address0,
        O_row_5_ce0,
        O_row_5_q0,
        O_row_6_address0,
        O_row_6_ce0,
        O_row_6_q0,
        O_row_7_address0,
        O_row_7_ce0,
        O_row_7_q0,
        O_row_8_address0,
        O_row_8_ce0,
        O_row_8_q0,
        O_row_9_address0,
        O_row_9_ce0,
        O_row_9_q0,
        O_row_10_address0,
        O_row_10_ce0,
        O_row_10_q0,
        O_row_11_address0,
        O_row_11_ce0,
        O_row_11_q0,
        O_row_12_address0,
        O_row_12_ce0,
        O_row_12_q0,
        O_row_13_address0,
        O_row_13_ce0,
        O_row_13_q0,
        O_row_14_address0,
        O_row_14_ce0,
        O_row_14_q0,
        O_row_15_address0,
        O_row_15_ce0,
        O_row_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_o_0_AWVALID;
input   m_axi_gmem_o_0_AWREADY;
output  [63:0] m_axi_gmem_o_0_AWADDR;
output  [0:0] m_axi_gmem_o_0_AWID;
output  [31:0] m_axi_gmem_o_0_AWLEN;
output  [2:0] m_axi_gmem_o_0_AWSIZE;
output  [1:0] m_axi_gmem_o_0_AWBURST;
output  [1:0] m_axi_gmem_o_0_AWLOCK;
output  [3:0] m_axi_gmem_o_0_AWCACHE;
output  [2:0] m_axi_gmem_o_0_AWPROT;
output  [3:0] m_axi_gmem_o_0_AWQOS;
output  [3:0] m_axi_gmem_o_0_AWREGION;
output  [0:0] m_axi_gmem_o_0_AWUSER;
output   m_axi_gmem_o_0_WVALID;
input   m_axi_gmem_o_0_WREADY;
output  [31:0] m_axi_gmem_o_0_WDATA;
output  [3:0] m_axi_gmem_o_0_WSTRB;
output   m_axi_gmem_o_0_WLAST;
output  [0:0] m_axi_gmem_o_0_WID;
output  [0:0] m_axi_gmem_o_0_WUSER;
output   m_axi_gmem_o_0_ARVALID;
input   m_axi_gmem_o_0_ARREADY;
output  [63:0] m_axi_gmem_o_0_ARADDR;
output  [0:0] m_axi_gmem_o_0_ARID;
output  [31:0] m_axi_gmem_o_0_ARLEN;
output  [2:0] m_axi_gmem_o_0_ARSIZE;
output  [1:0] m_axi_gmem_o_0_ARBURST;
output  [1:0] m_axi_gmem_o_0_ARLOCK;
output  [3:0] m_axi_gmem_o_0_ARCACHE;
output  [2:0] m_axi_gmem_o_0_ARPROT;
output  [3:0] m_axi_gmem_o_0_ARQOS;
output  [3:0] m_axi_gmem_o_0_ARREGION;
output  [0:0] m_axi_gmem_o_0_ARUSER;
input   m_axi_gmem_o_0_RVALID;
output   m_axi_gmem_o_0_RREADY;
input  [31:0] m_axi_gmem_o_0_RDATA;
input   m_axi_gmem_o_0_RLAST;
input  [0:0] m_axi_gmem_o_0_RID;
input  [8:0] m_axi_gmem_o_0_RFIFONUM;
input  [0:0] m_axi_gmem_o_0_RUSER;
input  [1:0] m_axi_gmem_o_0_RRESP;
input   m_axi_gmem_o_0_BVALID;
output   m_axi_gmem_o_0_BREADY;
input  [1:0] m_axi_gmem_o_0_BRESP;
input  [0:0] m_axi_gmem_o_0_BID;
input  [0:0] m_axi_gmem_o_0_BUSER;
input  [61:0] sext_ln107;
output  [1:0] O_row_address0;
output   O_row_ce0;
input  [31:0] O_row_q0;
output  [1:0] O_row_1_address0;
output   O_row_1_ce0;
input  [31:0] O_row_1_q0;
output  [1:0] O_row_2_address0;
output   O_row_2_ce0;
input  [31:0] O_row_2_q0;
output  [1:0] O_row_3_address0;
output   O_row_3_ce0;
input  [31:0] O_row_3_q0;
output  [1:0] O_row_4_address0;
output   O_row_4_ce0;
input  [31:0] O_row_4_q0;
output  [1:0] O_row_5_address0;
output   O_row_5_ce0;
input  [31:0] O_row_5_q0;
output  [1:0] O_row_6_address0;
output   O_row_6_ce0;
input  [31:0] O_row_6_q0;
output  [1:0] O_row_7_address0;
output   O_row_7_ce0;
input  [31:0] O_row_7_q0;
output  [1:0] O_row_8_address0;
output   O_row_8_ce0;
input  [31:0] O_row_8_q0;
output  [1:0] O_row_9_address0;
output   O_row_9_ce0;
input  [31:0] O_row_9_q0;
output  [1:0] O_row_10_address0;
output   O_row_10_ce0;
input  [31:0] O_row_10_q0;
output  [1:0] O_row_11_address0;
output   O_row_11_ce0;
input  [31:0] O_row_11_q0;
output  [1:0] O_row_12_address0;
output   O_row_12_ce0;
input  [31:0] O_row_12_q0;
output  [1:0] O_row_13_address0;
output   O_row_13_ce0;
input  [31:0] O_row_13_q0;
output  [1:0] O_row_14_address0;
output   O_row_14_ce0;
input  [31:0] O_row_14_q0;
output  [1:0] O_row_15_address0;
output   O_row_15_ce0;
input  [31:0] O_row_15_q0;

reg ap_idle;
reg m_axi_gmem_o_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln107_fu_360_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_o_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln107_fu_372_p1;
reg   [3:0] trunc_ln107_reg_504;
wire   [31:0] tmp_fu_411_p35;
reg   [31:0] tmp_reg_589;
wire   [63:0] zext_ln107_fu_386_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [6:0] j_fu_122;
wire   [6:0] add_ln107_fu_366_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1;
reg    O_row_ce0_local;
reg    O_row_1_ce0_local;
reg    O_row_2_ce0_local;
reg    O_row_3_ce0_local;
reg    O_row_4_ce0_local;
reg    O_row_5_ce0_local;
reg    O_row_6_ce0_local;
reg    O_row_7_ce0_local;
reg    O_row_8_ce0_local;
reg    O_row_9_ce0_local;
reg    O_row_10_ce0_local;
reg    O_row_11_ce0_local;
reg    O_row_12_ce0_local;
reg    O_row_13_ce0_local;
reg    O_row_14_ce0_local;
reg    O_row_15_ce0_local;
wire   [1:0] lshr_ln1_fu_376_p4;
wire   [31:0] tmp_fu_411_p33;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_fu_411_p1;
wire   [3:0] tmp_fu_411_p3;
wire   [3:0] tmp_fu_411_p5;
wire   [3:0] tmp_fu_411_p7;
wire   [3:0] tmp_fu_411_p9;
wire   [3:0] tmp_fu_411_p11;
wire   [3:0] tmp_fu_411_p13;
wire   [3:0] tmp_fu_411_p15;
wire  signed [3:0] tmp_fu_411_p17;
wire  signed [3:0] tmp_fu_411_p19;
wire  signed [3:0] tmp_fu_411_p21;
wire  signed [3:0] tmp_fu_411_p23;
wire  signed [3:0] tmp_fu_411_p25;
wire  signed [3:0] tmp_fu_411_p27;
wire  signed [3:0] tmp_fu_411_p29;
wire  signed [3:0] tmp_fu_411_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_122 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mhsa_top_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U675(
    .din0(O_row_q0),
    .din1(O_row_1_q0),
    .din2(O_row_2_q0),
    .din3(O_row_3_q0),
    .din4(O_row_4_q0),
    .din5(O_row_5_q0),
    .din6(O_row_6_q0),
    .din7(O_row_7_q0),
    .din8(O_row_8_q0),
    .din9(O_row_9_q0),
    .din10(O_row_10_q0),
    .din11(O_row_11_q0),
    .din12(O_row_12_q0),
    .din13(O_row_13_q0),
    .din14(O_row_14_q0),
    .din15(O_row_15_q0),
    .def(tmp_fu_411_p33),
    .sel(trunc_ln107_reg_504),
    .dout(tmp_fu_411_p35)
);

mhsa_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln107_fu_360_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_122 <= add_ln107_fu_366_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_122 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_reg_589 <= tmp_fu_411_p35;
        trunc_ln107_reg_504 <= trunc_ln107_fu_372_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_10_ce0_local = 1'b1;
    end else begin
        O_row_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_11_ce0_local = 1'b1;
    end else begin
        O_row_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_12_ce0_local = 1'b1;
    end else begin
        O_row_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_13_ce0_local = 1'b1;
    end else begin
        O_row_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_14_ce0_local = 1'b1;
    end else begin
        O_row_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_15_ce0_local = 1'b1;
    end else begin
        O_row_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_1_ce0_local = 1'b1;
    end else begin
        O_row_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_2_ce0_local = 1'b1;
    end else begin
        O_row_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_3_ce0_local = 1'b1;
    end else begin
        O_row_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_4_ce0_local = 1'b1;
    end else begin
        O_row_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_5_ce0_local = 1'b1;
    end else begin
        O_row_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_6_ce0_local = 1'b1;
    end else begin
        O_row_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_7_ce0_local = 1'b1;
    end else begin
        O_row_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_8_ce0_local = 1'b1;
    end else begin
        O_row_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_9_ce0_local = 1'b1;
    end else begin
        O_row_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        O_row_ce0_local = 1'b1;
    end else begin
        O_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln107_fu_360_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_o_blk_n_W = m_axi_gmem_o_0_WREADY;
    end else begin
        gmem_o_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem_o_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_o_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign O_row_10_address0 = zext_ln107_fu_386_p1;

assign O_row_10_ce0 = O_row_10_ce0_local;

assign O_row_11_address0 = zext_ln107_fu_386_p1;

assign O_row_11_ce0 = O_row_11_ce0_local;

assign O_row_12_address0 = zext_ln107_fu_386_p1;

assign O_row_12_ce0 = O_row_12_ce0_local;

assign O_row_13_address0 = zext_ln107_fu_386_p1;

assign O_row_13_ce0 = O_row_13_ce0_local;

assign O_row_14_address0 = zext_ln107_fu_386_p1;

assign O_row_14_ce0 = O_row_14_ce0_local;

assign O_row_15_address0 = zext_ln107_fu_386_p1;

assign O_row_15_ce0 = O_row_15_ce0_local;

assign O_row_1_address0 = zext_ln107_fu_386_p1;

assign O_row_1_ce0 = O_row_1_ce0_local;

assign O_row_2_address0 = zext_ln107_fu_386_p1;

assign O_row_2_ce0 = O_row_2_ce0_local;

assign O_row_3_address0 = zext_ln107_fu_386_p1;

assign O_row_3_ce0 = O_row_3_ce0_local;

assign O_row_4_address0 = zext_ln107_fu_386_p1;

assign O_row_4_ce0 = O_row_4_ce0_local;

assign O_row_5_address0 = zext_ln107_fu_386_p1;

assign O_row_5_ce0 = O_row_5_ce0_local;

assign O_row_6_address0 = zext_ln107_fu_386_p1;

assign O_row_6_ce0 = O_row_6_ce0_local;

assign O_row_7_address0 = zext_ln107_fu_386_p1;

assign O_row_7_ce0 = O_row_7_ce0_local;

assign O_row_8_address0 = zext_ln107_fu_386_p1;

assign O_row_8_ce0 = O_row_8_ce0_local;

assign O_row_9_address0 = zext_ln107_fu_386_p1;

assign O_row_9_ce0 = O_row_9_ce0_local;

assign O_row_address0 = zext_ln107_fu_386_p1;

assign O_row_ce0 = O_row_ce0_local;

assign add_ln107_fu_366_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_o_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_o_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_o_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln107_fu_360_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_376_p4 = {{ap_sig_allocacmp_j_1[5:4]}};

assign m_axi_gmem_o_0_ARADDR = 64'd0;

assign m_axi_gmem_o_0_ARBURST = 2'd0;

assign m_axi_gmem_o_0_ARCACHE = 4'd0;

assign m_axi_gmem_o_0_ARID = 1'd0;

assign m_axi_gmem_o_0_ARLEN = 32'd0;

assign m_axi_gmem_o_0_ARLOCK = 2'd0;

assign m_axi_gmem_o_0_ARPROT = 3'd0;

assign m_axi_gmem_o_0_ARQOS = 4'd0;

assign m_axi_gmem_o_0_ARREGION = 4'd0;

assign m_axi_gmem_o_0_ARSIZE = 3'd0;

assign m_axi_gmem_o_0_ARUSER = 1'd0;

assign m_axi_gmem_o_0_ARVALID = 1'b0;

assign m_axi_gmem_o_0_AWADDR = 64'd0;

assign m_axi_gmem_o_0_AWBURST = 2'd0;

assign m_axi_gmem_o_0_AWCACHE = 4'd0;

assign m_axi_gmem_o_0_AWID = 1'd0;

assign m_axi_gmem_o_0_AWLEN = 32'd0;

assign m_axi_gmem_o_0_AWLOCK = 2'd0;

assign m_axi_gmem_o_0_AWPROT = 3'd0;

assign m_axi_gmem_o_0_AWQOS = 4'd0;

assign m_axi_gmem_o_0_AWREGION = 4'd0;

assign m_axi_gmem_o_0_AWSIZE = 3'd0;

assign m_axi_gmem_o_0_AWUSER = 1'd0;

assign m_axi_gmem_o_0_AWVALID = 1'b0;

assign m_axi_gmem_o_0_BREADY = 1'b0;

assign m_axi_gmem_o_0_RREADY = 1'b0;

assign m_axi_gmem_o_0_WDATA = tmp_reg_589;

assign m_axi_gmem_o_0_WID = 1'd0;

assign m_axi_gmem_o_0_WLAST = 1'b0;

assign m_axi_gmem_o_0_WSTRB = 4'd15;

assign m_axi_gmem_o_0_WUSER = 1'd0;

assign tmp_fu_411_p33 = 'bx;

assign trunc_ln107_fu_372_p1 = ap_sig_allocacmp_j_1[3:0];

assign zext_ln107_fu_386_p1 = lshr_ln1_fu_376_p4;

endmodule //mhsa_top_mhsa_top_Pipeline_store_o
