# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/projects/vit_base16/vivado_workspace/vivado_workspace.srcs/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/mhsa_mhsa_top_0_0.xci
# IP: The module: 'mhsa_mhsa_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/hdl/ip/mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip/mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip || ORIG_REF_NAME==mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip} -quiet] -quiet

# IP: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/hdl/ip/mhsa_top_fpext_32ns_64_2_no_dsp_1_ip/mhsa_top_fpext_32ns_64_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==mhsa_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/constraints/mhsa_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mhsa_mhsa_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/projects/vit_base16/vivado_workspace/vivado_workspace.srcs/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/mhsa_mhsa_top_0_0.xci
# IP: The module: 'mhsa_mhsa_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/hdl/ip/mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip/mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip || ORIG_REF_NAME==mhsa_top_fdiv_32ns_32ns_32_9_no_dsp_1_ip} -quiet] -quiet

# IP: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/hdl/ip/mhsa_top_fpext_32ns_64_2_no_dsp_1_ip/mhsa_top_fpext_32ns_64_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mhsa_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==mhsa_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/projects/vit_base16/vivado_workspace/vivado_workspace.gen/sources_1/bd/mhsa/ip/mhsa_mhsa_top_0_0/constraints/mhsa_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mhsa_mhsa_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
