[hls]
relative_roots=C:/projects/vit_base16/vit_base16
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=mhsa_top/load_kv  
syn.directive.array_partition=mhsa_top/EXP_LUT dim=1 type=complete variable=EXP_LUT
syn.directive.array_partition=mhsa_top/RES_LUT dim=1 type=complete variable=RES_LUT


