-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Wed Aug 26 14:01:29 2026
-- Host        : NAV running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ mhsa_mhsa_top_0_0_stub.vhdl
-- Design      : mhsa_mhsa_top_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu7ev-ffvc1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem_q_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_q_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_q_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_q_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_q_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_ARREADY : in STD_LOGIC;
    m_axi_gmem_q_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_q_ARVALID : out STD_LOGIC;
    m_axi_gmem_q_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_q_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_q_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_q_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_q_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_AWREADY : in STD_LOGIC;
    m_axi_gmem_q_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_q_AWVALID : out STD_LOGIC;
    m_axi_gmem_q_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_q_BREADY : out STD_LOGIC;
    m_axi_gmem_q_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_BVALID : in STD_LOGIC;
    m_axi_gmem_q_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_q_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_q_RLAST : in STD_LOGIC;
    m_axi_gmem_q_RREADY : out STD_LOGIC;
    m_axi_gmem_q_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_q_RVALID : in STD_LOGIC;
    m_axi_gmem_q_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_q_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_q_WLAST : out STD_LOGIC;
    m_axi_gmem_q_WREADY : in STD_LOGIC;
    m_axi_gmem_q_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_q_WVALID : out STD_LOGIC;
    m_axi_gmem_k_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_k_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_k_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_k_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_k_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_ARREADY : in STD_LOGIC;
    m_axi_gmem_k_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_k_ARVALID : out STD_LOGIC;
    m_axi_gmem_k_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_k_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_k_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_k_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_k_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_AWREADY : in STD_LOGIC;
    m_axi_gmem_k_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_k_AWVALID : out STD_LOGIC;
    m_axi_gmem_k_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_k_BREADY : out STD_LOGIC;
    m_axi_gmem_k_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_BVALID : in STD_LOGIC;
    m_axi_gmem_k_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_k_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_k_RLAST : in STD_LOGIC;
    m_axi_gmem_k_RREADY : out STD_LOGIC;
    m_axi_gmem_k_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_k_RVALID : in STD_LOGIC;
    m_axi_gmem_k_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_k_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_k_WLAST : out STD_LOGIC;
    m_axi_gmem_k_WREADY : in STD_LOGIC;
    m_axi_gmem_k_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_k_WVALID : out STD_LOGIC;
    m_axi_gmem_v_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_v_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_v_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_v_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_v_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_ARREADY : in STD_LOGIC;
    m_axi_gmem_v_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_v_ARVALID : out STD_LOGIC;
    m_axi_gmem_v_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_v_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_v_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_v_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_v_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_AWREADY : in STD_LOGIC;
    m_axi_gmem_v_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_v_AWVALID : out STD_LOGIC;
    m_axi_gmem_v_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_v_BREADY : out STD_LOGIC;
    m_axi_gmem_v_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_BVALID : in STD_LOGIC;
    m_axi_gmem_v_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_v_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_v_RLAST : in STD_LOGIC;
    m_axi_gmem_v_RREADY : out STD_LOGIC;
    m_axi_gmem_v_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_v_RVALID : in STD_LOGIC;
    m_axi_gmem_v_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_v_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_v_WLAST : out STD_LOGIC;
    m_axi_gmem_v_WREADY : in STD_LOGIC;
    m_axi_gmem_v_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_v_WVALID : out STD_LOGIC;
    m_axi_gmem_o_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_o_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_o_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_o_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_o_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_ARREADY : in STD_LOGIC;
    m_axi_gmem_o_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_o_ARVALID : out STD_LOGIC;
    m_axi_gmem_o_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_o_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_o_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_o_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_o_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_AWREADY : in STD_LOGIC;
    m_axi_gmem_o_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_o_AWVALID : out STD_LOGIC;
    m_axi_gmem_o_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_o_BREADY : out STD_LOGIC;
    m_axi_gmem_o_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_BVALID : in STD_LOGIC;
    m_axi_gmem_o_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_o_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_o_RLAST : in STD_LOGIC;
    m_axi_gmem_o_RREADY : out STD_LOGIC;
    m_axi_gmem_o_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_o_RVALID : in STD_LOGIC;
    m_axi_gmem_o_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_o_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_o_WLAST : out STD_LOGIC;
    m_axi_gmem_o_WREADY : in STD_LOGIC;
    m_axi_gmem_o_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_o_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "mhsa_mhsa_top_0_0,mhsa_top,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "mhsa_mhsa_top_0_0,mhsa_top,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=mhsa_top,x_ipVersion=1.0,x_ipCoreRevision=2114758211,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=7,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_GMEM_Q_ID_WIDTH=1,C_M_AXI_GMEM_Q_ADDR_WIDTH=64,C_M_AXI_GMEM_Q_DATA_WIDTH=32,C_M_AXI_GMEM_Q_AWUSER_WIDTH=1,C_M_AXI_GMEM_Q_ARUSER_WIDTH=1,C_M_AXI_GMEM_Q_WUSER_WIDTH=1,C_M_AXI_GMEM_Q_RUSER_WIDTH=1,C_M_AXI_GMEM_Q_BUSER_WIDTH=1,C_M_AXI_GMEM_Q_USER_VALUE=0x00000000,C_M_AXI_GMEM_Q_PROT_VALUE=000,C_M_AXI_GMEM_Q_CACHE_VALUE=0011,C_M_AXI_GMEM_K_ID_WIDTH=1,C_M_AXI_GMEM_K_ADDR_WIDTH=64,C_M_AXI_GMEM_K_DATA_WIDTH=32,C_M_AXI_GMEM_K_AWUSER_WIDTH=1,C_M_AXI_GMEM_K_ARUSER_WIDTH=1,C_M_AXI_GMEM_K_WUSER_WIDTH=1,C_M_AXI_GMEM_K_RUSER_WIDTH=1,C_M_AXI_GMEM_K_BUSER_WIDTH=1,C_M_AXI_GMEM_K_USER_VALUE=0x00000000,C_M_AXI_GMEM_K_PROT_VALUE=000,C_M_AXI_GMEM_K_CACHE_VALUE=0011,C_M_AXI_GMEM_V_ID_WIDTH=1,C_M_AXI_GMEM_V_ADDR_WIDTH=64,C_M_AXI_GMEM_V_DATA_WIDTH=32,C_M_AXI_GMEM_V_AWUSER_WIDTH=1,C_M_AXI_GMEM_V_ARUSER_WIDTH=1,C_M_AXI_GMEM_V_WUSER_WIDTH=1,C_M_AXI_GMEM_V_RUSER_WIDTH=1,C_M_AXI_GMEM_V_BUSER_WIDTH=1,C_M_AXI_GMEM_V_USER_VALUE=0x00000000,C_M_AXI_GMEM_V_PROT_VALUE=000,C_M_AXI_GMEM_V_CACHE_VALUE=0011,C_M_AXI_GMEM_O_ID_WIDTH=1,C_M_AXI_GMEM_O_ADDR_WIDTH=64,C_M_AXI_GMEM_O_DATA_WIDTH=32,C_M_AXI_GMEM_O_AWUSER_WIDTH=1,C_M_AXI_GMEM_O_ARUSER_WIDTH=1,C_M_AXI_GMEM_O_WUSER_WIDTH=1,C_M_AXI_GMEM_O_RUSER_WIDTH=1,C_M_AXI_GMEM_O_BUSER_WIDTH=1,C_M_AXI_GMEM_O_USER_VALUE=0x00000000,C_M_AXI_GMEM_O_PROT_VALUE=000,C_M_AXI_GMEM_O_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[6:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[6:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_gmem_q_ARADDR[63:0],m_axi_gmem_q_ARBURST[1:0],m_axi_gmem_q_ARCACHE[3:0],m_axi_gmem_q_ARID[0:0],m_axi_gmem_q_ARLEN[7:0],m_axi_gmem_q_ARLOCK[1:0],m_axi_gmem_q_ARPROT[2:0],m_axi_gmem_q_ARQOS[3:0],m_axi_gmem_q_ARREADY,m_axi_gmem_q_ARREGION[3:0],m_axi_gmem_q_ARSIZE[2:0],m_axi_gmem_q_ARVALID,m_axi_gmem_q_AWADDR[63:0],m_axi_gmem_q_AWBURST[1:0],m_axi_gmem_q_AWCACHE[3:0],m_axi_gmem_q_AWID[0:0],m_axi_gmem_q_AWLEN[7:0],m_axi_gmem_q_AWLOCK[1:0],m_axi_gmem_q_AWPROT[2:0],m_axi_gmem_q_AWQOS[3:0],m_axi_gmem_q_AWREADY,m_axi_gmem_q_AWREGION[3:0],m_axi_gmem_q_AWSIZE[2:0],m_axi_gmem_q_AWVALID,m_axi_gmem_q_BID[0:0],m_axi_gmem_q_BREADY,m_axi_gmem_q_BRESP[1:0],m_axi_gmem_q_BVALID,m_axi_gmem_q_RDATA[31:0],m_axi_gmem_q_RID[0:0],m_axi_gmem_q_RLAST,m_axi_gmem_q_RREADY,m_axi_gmem_q_RRESP[1:0],m_axi_gmem_q_RVALID,m_axi_gmem_q_WDATA[31:0],m_axi_gmem_q_WID[0:0],m_axi_gmem_q_WLAST,m_axi_gmem_q_WREADY,m_axi_gmem_q_WSTRB[3:0],m_axi_gmem_q_WVALID,m_axi_gmem_k_ARADDR[63:0],m_axi_gmem_k_ARBURST[1:0],m_axi_gmem_k_ARCACHE[3:0],m_axi_gmem_k_ARID[0:0],m_axi_gmem_k_ARLEN[7:0],m_axi_gmem_k_ARLOCK[1:0],m_axi_gmem_k_ARPROT[2:0],m_axi_gmem_k_ARQOS[3:0],m_axi_gmem_k_ARREADY,m_axi_gmem_k_ARREGION[3:0],m_axi_gmem_k_ARSIZE[2:0],m_axi_gmem_k_ARVALID,m_axi_gmem_k_AWADDR[63:0],m_axi_gmem_k_AWBURST[1:0],m_axi_gmem_k_AWCACHE[3:0],m_axi_gmem_k_AWID[0:0],m_axi_gmem_k_AWLEN[7:0],m_axi_gmem_k_AWLOCK[1:0],m_axi_gmem_k_AWPROT[2:0],m_axi_gmem_k_AWQOS[3:0],m_axi_gmem_k_AWREADY,m_axi_gmem_k_AWREGION[3:0],m_axi_gmem_k_AWSIZE[2:0],m_axi_gmem_k_AWVALID,m_axi_gmem_k_BID[0:0],m_axi_gmem_k_BREADY,m_axi_gmem_k_BRESP[1:0],m_axi_gmem_k_BVALID,m_axi_gmem_k_RDATA[31:0],m_axi_gmem_k_RID[0:0],m_axi_gmem_k_RLAST,m_axi_gmem_k_RREADY,m_axi_gmem_k_RRESP[1:0],m_axi_gmem_k_RVALID,m_axi_gmem_k_WDATA[31:0],m_axi_gmem_k_WID[0:0],m_axi_gmem_k_WLAST,m_axi_gmem_k_WREADY,m_axi_gmem_k_WSTRB[3:0],m_axi_gmem_k_WVALID,m_axi_gmem_v_ARADDR[63:0],m_axi_gmem_v_ARBURST[1:0],m_axi_gmem_v_ARCACHE[3:0],m_axi_gmem_v_ARID[0:0],m_axi_gmem_v_ARLEN[7:0],m_axi_gmem_v_ARLOCK[1:0],m_axi_gmem_v_ARPROT[2:0],m_axi_gmem_v_ARQOS[3:0],m_axi_gmem_v_ARREADY,m_axi_gmem_v_ARREGION[3:0],m_axi_gmem_v_ARSIZE[2:0],m_axi_gmem_v_ARVALID,m_axi_gmem_v_AWADDR[63:0],m_axi_gmem_v_AWBURST[1:0],m_axi_gmem_v_AWCACHE[3:0],m_axi_gmem_v_AWID[0:0],m_axi_gmem_v_AWLEN[7:0],m_axi_gmem_v_AWLOCK[1:0],m_axi_gmem_v_AWPROT[2:0],m_axi_gmem_v_AWQOS[3:0],m_axi_gmem_v_AWREADY,m_axi_gmem_v_AWREGION[3:0],m_axi_gmem_v_AWSIZE[2:0],m_axi_gmem_v_AWVALID,m_axi_gmem_v_BID[0:0],m_axi_gmem_v_BREADY,m_axi_gmem_v_BRESP[1:0],m_axi_gmem_v_BVALID,m_axi_gmem_v_RDATA[31:0],m_axi_gmem_v_RID[0:0],m_axi_gmem_v_RLAST,m_axi_gmem_v_RREADY,m_axi_gmem_v_RRESP[1:0],m_axi_gmem_v_RVALID,m_axi_gmem_v_WDATA[31:0],m_axi_gmem_v_WID[0:0],m_axi_gmem_v_WLAST,m_axi_gmem_v_WREADY,m_axi_gmem_v_WSTRB[3:0],m_axi_gmem_v_WVALID,m_axi_gmem_o_ARADDR[63:0],m_axi_gmem_o_ARBURST[1:0],m_axi_gmem_o_ARCACHE[3:0],m_axi_gmem_o_ARID[0:0],m_axi_gmem_o_ARLEN[7:0],m_axi_gmem_o_ARLOCK[1:0],m_axi_gmem_o_ARPROT[2:0],m_axi_gmem_o_ARQOS[3:0],m_axi_gmem_o_ARREADY,m_axi_gmem_o_ARREGION[3:0],m_axi_gmem_o_ARSIZE[2:0],m_axi_gmem_o_ARVALID,m_axi_gmem_o_AWADDR[63:0],m_axi_gmem_o_AWBURST[1:0],m_axi_gmem_o_AWCACHE[3:0],m_axi_gmem_o_AWID[0:0],m_axi_gmem_o_AWLEN[7:0],m_axi_gmem_o_AWLOCK[1:0],m_axi_gmem_o_AWPROT[2:0],m_axi_gmem_o_AWQOS[3:0],m_axi_gmem_o_AWREADY,m_axi_gmem_o_AWREGION[3:0],m_axi_gmem_o_AWSIZE[2:0],m_axi_gmem_o_AWVALID,m_axi_gmem_o_BID[0:0],m_axi_gmem_o_BREADY,m_axi_gmem_o_BRESP[1:0],m_axi_gmem_o_BVALID,m_axi_gmem_o_RDATA[31:0],m_axi_gmem_o_RID[0:0],m_axi_gmem_o_RLAST,m_axi_gmem_o_RREADY,m_axi_gmem_o_RRESP[1:0],m_axi_gmem_o_RVALID,m_axi_gmem_o_WDATA[31:0],m_axi_gmem_o_WID[0:0],m_axi_gmem_o_WLAST,m_axi_gmem_o_WREADY,m_axi_gmem_o_WSTRB[3:0],m_axi_gmem_o_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 7, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 96968727, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_gmem_q:m_axi_gmem_k:m_axi_gmem_v:m_axi_gmem_o, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 96968727, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_q_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_q_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_q, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_q_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_q WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_k_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_k_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_k, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_k_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_k WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_v_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_v_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_v, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_v_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_v WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_o_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_o_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_o, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 96968727, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN mhsa_zynq_ultra_ps_e_0_0_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_o_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_o WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "mhsa_top,Vivado 2025.2";
begin
end;
